# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    container_name: livrairie-mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: Shewbii
      ME_CONFIG_BASICAUTH_PASSWORD: 9qgtmngR!!